version: '3.8'

services:
  # Node.js application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://db:27017/myapp
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev  # Assuming you have a dev script with nodemon

  # Database (MongoDB example)
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: